### ISSUE TITLE
ActiveRecordConsumer to allow skipping messages based on condition

### ISSUE THREAD

**Issue by etam-pro** [flipp-oss/deimos#100]
`ActiveRecordConsumer` currently consumes everything from a topic. This could be devastating when handling large topics and you want to skip the processing of some of the messages that you don't care.

It would be great if we are allowed to override a predicate method e.g. `process_payload?` to allow conditionally skip some of the messages going through the consumer.

**Comment by csingh** [comment]
Feature has been added :)
