### ISSUE TITLE
Shut down sync producers if persistent_connections is set

### ISSUE THREAD

**Issue by dorner** [flipp-oss/deimos#11]
Currently Deimos shuts down async producers on app shutdown. Phobos 1.8.3 adds a `persistent_connections` setting so that even sync producers require shutdown. We should call that manually the same way we call async shutdown if that setting is set.

**Comment by csingh** [comment]
This has already been implemented:
https://github.com/flipp-oss/deimos/blob/master/lib/deimos/backends/kafka.rb#L11
