### ISSUE TITLE
Rubocop is enforcing `start_of_block` identation

### ISSUE THREAD

**Issue by randommancer** [flipp-oss/deimos#183]
Rubocop is enforcing `start_of_block` behaviour which is causing some weird indentation.
https://docs.rubocop.org/rubocop/cops_layout.html#layoutblockalignment

Here is one of the files:
https://github.com/flipp-oss/deimos/blob/47de2d597d45f4e187e0f23ad64fbb3691ddaa91/spec/active_record_batch_consumer_mysql_spec.rb#L243

The propose is to change to `start_of_line`

**Comment by dorner** [comment]
@randommancer what happened with this suggestion? Can the issue be closed?

**Comment by etam-pro** [comment]
@dorner i think we will settle with not changing anything as long as rubocop autocorrects for us.

**Comment by dorner** [comment]
Thanks!
