### ISSUE TITLE
Why not supporting headers?

### ISSUE THREAD

**Issue by yannp** [flipp-oss/deimos#192]
Hi,

I'm wondering about the purpose of [monkey_patches/phobos_producer.rb](https://github.com/flipp-oss/deimos/blame/master/lib/deimos/monkey_patches/phobos_producer.rb) dating from the initial commit which drops supports for message headers. This patch removes only removes headers support, that's very intentional.

Message headers are supported by phobos and by the underlying ruby-kafka and is a convenient way to add metadata to messages. What's the purpose of this patch?

**Comment by dorner** [comment]
Honestly? I don't even remember why that monkey patch is in there. It definitely wasn't to patch out header support - more likely the patch predates the header support.

We probably should remove it and see if anything breaks.
