### ISSUE TITLE
Do not call generate_payload when payload is nil

### ISSUE THREAD

**Issue by dorner** [flipp-oss/deimos#38]
In ActiveRecordConsumer, it will call `generate_payload` even when deleting a record and the payload consists of nothing but a `payload_key`. This should not call the method since there should be no payload to generate.

**Comment by csingh** [comment]
@dorner I don't see anything similar to `generate_payload` in ActiveRecordConsumer. Did you mean Producer? If so, is this a duplicate of #39 ?

**Comment by dorner** [comment]
Yep, this is a dupe. :p Destroying with extreme prejudice now.
