### ISSUE TITLE
Encoded Error Logging while consuming messages

### ISSUE THREAD

**Issue by aryanksingh108** [flipp-oss/deimos#66]
While testing the new deimos upgrade on Godfather, found an issue where error logging is not human readable in the metadata and data fields.
[Here](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=godfather-stg;stream=godfather-stg/godfather-stg/7eebcf75-0d02-4226-820b-205109806177;refid=35434750584759392206710735948099022300024686163048071170;reftime=1588949170501) is the link to a cloudwatch log showing the error logging.

**Comment by dorner** [comment]
Should be fixed in version 1.6.4: https://github.com/flipp-oss/deimos/commit/2a787a16ee15404a11bd7ea90935d1a8252fe6ae
